#pragma once

/* Generated with cbindgen:0.28.0 */

// This file is autogenerated by cbindgen. Don't modify it manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef enum ParseResults {
  ParserSuccess,
  ParserInvalidArgument,
  ParserError,
} ParseResults;

typedef enum RenderResults {
  RenderSuccess,
  RenderInvalidArgument,
  RenderError,
} RenderResults;

typedef struct ParserOptions ParserOptions;

typedef struct ParserOutput ParserOutput;

const char *mrml_last_error(void);

enum ParseResults new_parser_options(struct ParserOptions **parser);

enum ParseResults add_memory_loader(struct ParserOptions *parser_options,
                                    const char *key,
                                    const char *value);

enum ParseResults parse_json(struct ParserOptions *parser_options,
                             const char *input,
                             struct ParserOutput **output);

enum ParseResults parse_mjml(struct ParserOptions *parser_options,
                             const char *input,
                             struct ParserOutput **output);

enum RenderResults to_html(const struct ParserOutput *parser_output,
                           char **output);

enum RenderResults to_json(const struct ParserOutput *parser_output,
                           char **output);

enum RenderResults to_mjml(const struct ParserOutput *parser_output,
                           char **output);

void destroy_parser_options(struct ParserOptions *parser_options);

void destroy_parser_output(struct ParserOutput *parser_output);
